language: python
python:
  - "3.7"

# command to install dependencies
install:
  - pip install -r requirements-test.txt
  - pip install .

script:
  - py.test -v --cov=fastjmd95 --cov-config .coveragerc --cov-report term-missing

after_success:
  - codecov
