language: python
python:
  - "3.7"

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install .

script:
  - py.test -v --cov=xhistogram --cov-config .coveragerc --cov-report term-missing

after_success:
  - codecov
